### ISSUE TITLE
Add support for TLS when connecting to servers

### ISSUE THREAD

**Issue by pinaraf** [postgresml/pgcat#366]
**Is your feature request related to a problem? Please describe.**
PgCat doesn't allow connecting to a PostgreSQL server that requires TLS.

**Describe the solution you'd like**
PgCat should be able to send an SSLRequest message before StartupMessage to request TLS from the PostgreSQL server, thus making it usable even on "untrustable" networks.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by levkk** [comment]
There is an example on how to do that with the `Client` in `client.rs`. We'll just need to make `Server` the same way and negotiate a TLS connection :+1:
