### ISSUE TITLE
can't connect admin database with pgcli

### ISSUE THREAD

**Issue by jsvisa** [postgresml/pgcat#493]
**Describe the bug**

I'm connecting the pgcat admin database with [pgcli](https://github.com/dbcli/pgcli), and failed with the error below:

```
$ pgcli -h 127.0.0.1 -p 6432 -U postgres -d pgcat
Password for postgres:
Unsupported query against the admin database
```

BTW, use pgcli to connect pgcat pools was succeed.

pgcli: v3.5.0
pgcat: ghcr.io/postgresml/pgcat:latest@6a688c2b7ce4

**Comment by levkk** [comment]
I don't use pgcli, but I suspect it's running some startup queries automatically for you. Use `psql` to connect to the admin database instead.
