### ISSUE TITLE
Sharding tests do not work (using default settings)

### ISSUE THREAD

**Issue by mdashti** [postgresml/pgcat#535]
**Describe the bug**

**To Reproduce**
1. Switch to the recent commit on `main` @ 9d1c46a3e9a672d3bb2709ded8a814c5f07fa8b8
2. Follow the instructions in the https://github.com/postgresml/pgcat/blob/main/tests/sharding/README.md
  - start a postgres server
  - run `psql -f query_routing_setup.sql`
  - start up PgCat by running `cargo run --release` in the root of the repo
  -  run `psql -h 127.0.0.1 -p 6432 -f query_routing_test_insert.sql`
    - this command does not work, and I run this one instead: `PGPASSWORD=sharding_user psql sharded_db -h 127.0.0.1 -p 6432 -U sharding_user -f query_routing_test_insert.sql` 

**Expected behavior**
It's expected for the test to run successfully. However, it fails with:

```

SET SHARDING KEY
INSERT 0 1
psql:query_routing_test_insert.sql:6: ERROR:  syntax error at or near "KEY"
LINE 1: SET SHARDING KEY TO '2';
                     ^

```

**Desktop**
 - OS: macOS
 - Version: 1.1.1 (`main` @ 9d1c46a3e9a672d3bb2709ded8a814c5f07fa8b8)

**Comment by mdashti** [comment]
This diff fixes the issue:

```
diff --git a/pgcat.toml b/pgcat.toml
index 3e8801b..d8ed108 100644
--- a/pgcat.toml
+++ b/pgcat.toml
@@ -270,7 +270,7 @@ username = "sharding_user"
 # if `server_password` is not set.
 password = "sharding_user"
 
-pool_mode = "session"
+pool_mode = "transaction"
 
 # PostgreSQL username used to connect to the server.
 # server_username = "another_user"
```

**Comment by levkk** [comment]
Could you submit a PR with the fix if you have a moment?
