### ISSUE TITLE
[Q]  query_parser_enabled  & plugins ?

### ISSUE THREAD

**Issue by hellower** [postgresml/pgcat#576]
1) pgcat 1.1.1 (works good)
```
..............
[pools.tarantula]
pool_mode = "session"   # for set application_name=xxxx
default_role = "any"
query_parser_enabled = false   ### FALSE !!!
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"


[pool.tarantula.plugins]
[pools.tarantula.plugins.prewarmer]
enabled = true
queries = [
  "select /*t*/ plv8_version()",
]
..............
```

2) pgcat 1.1.2-dev (# ERROR pgcat::config: plugins are only valid when query_parser_enabled is true )

```
..............
[pools.tarantula]
pool_mode = "session"   # for set application_name=xxxx
default_role = "any"
query_parser_enabled = false  # ERROR pgcat::config: plugins are only valid when query_parser_enabled is true 
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"


[pool.tarantula.plugins]
[pools.tarantula.plugins.prewarmer]
enabled = true
queries = [
  "select /*t*/ plv8_version()",
]
..............
```

Why does "query_parser_enabled" have to be true when using plugins?
There doesn't seem to be any correlation between the two.

**Comment by levkk** [comment]
Query parser uses SQL parsing to create an Abstract Syntax Tree (AST) of the query. Plugins work with the AST to figure out what to do, e.g. accept the query, rewrite the query, etc. Without the query parser, plugins can't work. I agree that the configuration validation is not very intuitive. We may want to enable the query parser automatically if the plugins are enabled.

**Comment by hellower** [comment]
Thanks!
