### ISSUE TITLE
Health check command

### ISSUE THREAD

**Issue by adriangb** [postgresml/pgcat#685]
**Is your feature request related to a problem? Please describe.**

When deploying it's good to have some sort of healthcheck.

**Describe the solution you'd like**

A command (binary) like `pgcat health <some connection info?` that can be set up as an exec probe on k8s deployments.

**Describe alternatives you've considered**

Rebuilding the image myself to include e.g. `psql` so I can use that as a probe.
This has the con of requiring a rebuild on my end, bloating the image and having to figure out what username/password I'm going to use, etc. (probably the admin username/password makes sense).

**Comment by rmenn** [comment]
it has been added in #607 i dont believe there has been a release after, if you pull the latest image its present 

```
root@a6f7cd205063:/etc/pgcat# which psql 
/usr/bin/psql
```

**Comment by adriangb** [comment]
Nice!
