### ISSUE TITLE
request:release plan for pgcat in PostgreSQL 16

### ISSUE THREAD

**Issue by seunofk** [postgresml/pgcat#690]
Hello, guys. :)

Is there any release plan for pgcat in PostgreSQL 16?

I'm interested in testing A-A setup using pgcat in a PostgreSQL 16 logical replication environment.

It seems like the Docker version is 15, so could you share any updates?

If asking about this because I'm not very familiar with using git is impolite, I apologize.

**Comment by levkk** [comment]
Hello,

Pgcat doesn't need anything special to support Postgres 16. The protocol hasn't changed between Pg 15 and Pg 16 in anyway that I can think of that would affect PgCat operations. Please let me know if you see any issues in your deployment of Pg 16 and feel free to re-open this issue.
