### ISSUE TITLE
The docs don't link to the APT Repository for pgcat

### ISSUE THREAD

**Issue by jardayn** [postgresml/pgcat#719]
https://postgresml.org/docs/product/pgcat/installation

The repository isn't linked here, nor in the README of the repo.

**Comment by levkk** [comment]
Here you go: https://postgresml.org/docs/resources/developer-docs/self-hosting/#installing-postgres-ml

**Comment by jardayn** [comment]
> Here you go: https://postgresml.org/docs/resources/developer-docs/self-hosting/#installing-postgres-ml

Thank you, Lev! :)
