### ISSUE TITLE
[Question] Pgcat not found in Artifact Hub 

### ISSUE THREAD

**Issue by vivaticket-gpatane** [postgresml/pgcat#763]
I was planning to deploy PGCAT via your helm cart. However, it appears that it was removed from the artifacthub.io.  Is there a reason why  it was removed?  how can I deploy pgcat via helm?

![image](https://github.com/postgresml/pgcat/assets/83081983/d9fca5be-bd3b-4b91-947d-7974df56ad4d)

![image](https://github.com/postgresml/pgcat/assets/83081983/f36e4b40-cd3d-4ed3-94ea-e3ec81bc673d)

**Comment by drdrsh** [comment]
I see it now.  Not sure what happened there

![Screenshot from 2024-08-31 15-48-08](https://github.com/user-attachments/assets/f4344180-e498-4200-9f2a-1b27700897be)
