### ISSUE TITLE
Does PGCAT support environment variables in the pgcat.toml file

### ISSUE THREAD

**Issue by asnimansari** [postgresml/pgcat#764]
Couldn't find any information about passing environment variables to fill fields in `pgcat.toml` file.

Is it expected to hardcode the db creds in `pgcat` or is there a way to pass it via env?

**Comment by levkk** [comment]
No env variables support in the config. We would be better off supporting loading secrets (passwords, etc) from a separate file. Currently, `pgcat.tom`l is considered a secret and should be treated as such, e.g. stored in Vault, K8s secret, etc.
