### ISSUE TITLE
pgcat to database connection count

### ISSUE THREAD

**Issue by devopscloudnexus** [postgresml/pgcat#770]
Folks, can we control the count of connections that pgcat makes to the database?
We are using "pool_size" to control the count of connections that pgcat would accept from the applications. Still, this count is generally high and our database gets into "too many connections" situations. 

**Describe the solution you'd like**
A parameter like "db_connection_size" that can restrict max number of connections that pgcat can open.

**Describe alternatives you've considered**
None. We are using monitoring to raise alarm when connections on db increase

**Comment by drdrsh** [comment]
`pool_size` is the maximum number of connections that PgCat opens per instance so it should be behaving exactly as what you want.

You may want to check if you have clients that are connecting directly to your database or if you are running PgCat in a high availability setup (running more than one PgCat instance behind a load balancer).
