### ISSUE TITLE
Sharding mode a select statement without any filters not scan all sharding database 

### ISSUE THREAD

**Issue by status-code-404** [postgresml/pgcat#771]
I make two shards to test sharding function. When I start a select with sharding key, It can act as I expected use the right shard connection to handle sql. But when I select using other field or no fliters, it only gives me one sharding db result. I find that in client.rs, each handle func only get one shard connections, which means result only contains one sharding db results determines by default_shard config. 
What I expected is PgCat will execute queries against all shards in parallel, combine the results, and return all of them as part of the same request.
Is that my config file has problem? or something wrong that I use it?

(follow image I use default_shard="random" so you can see different result in search because of two times connection to different db)
![2024-07-30_23-30](https://github.com/user-attachments/assets/a93885a6-d517-480b-b7fe-07323173a876)

and following is my config
```
[pools.local_test]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "primary"
default_shard = "random"
query_parser_enabled = true
query_parser_read_write_splitting = true
primary_reads_enabled = true
connect_timeout = 3000
sharding_function = "pg_bigint_hash"
automatic_sharding_key = "db.db_id"

[pools.local_test.shards.0]
servers = [["127.0.0.1", 8001, "primary"]]
database = "sharding_test"

[pools.local_test.shards.1]
servers = [["127.0.0.1", 8002, "primary"]]
database = "sharding_test"
```

Thank you.

**Comment by zainkabani** [comment]
>What I expected is PgCat will execute queries against all shards in parallel, combine the results, and return all of them as part of the same request

PgCat does not support this type of aggregation at this time, you would need to query each shard and do the aggregation on the client

**Comment by status-code-404** [comment]
> > What I expected is PgCat will execute queries against all shards in parallel, combine the results, and return all of them as part of the same request
> 
> PgCat does not support this type of aggregation at this time, you would need to query each shard and do the aggregation on the client

ok thanks
