### ISSUE TITLE
sharding on schema

### ISSUE THREAD

**Issue by DeoLeung** [postgresml/pgcat#78]
**Is your feature request related to a problem? Please describe.**

We use postgres schema heavily to support multi-tenant, like `schema_1` for company 1, `schema_2` for company 2, they have identical table set, and other schemas like `data` to contain share tables. however when the business grows, the database gets bigger and bigger and tenants will compete the database resource.

**Describe the solution you'd like**

I want to manually shard by schema. something like (though I think it's more like locating  a target database :)
```bash
-- Grab a bunch of users from db 1
SET SHARD TO 'schema_1';
SELECT * FROM users LIMT 10;
-- similar to SELECT * FROM schema_1.users LIMT 10;

-- we can duplicate some share data on schema_1's database, so i could be queried
SET SHARD TO 'schema_1'
SELECT * FROM data.info_abc WHERE id = 1234;
```

we use full identifier for tables, like always include the schema part, if the routing could be done automatically, that will be much better!

and for the share data, if we can avoid duplicating them, instead auto `fdw` to use them will be great (but I think there will be some  performance problem)

**Describe alternatives you've considered**

I'm trying `shardingsphere-proxy==5.1.2`, haven't succeeded yet

**Comment by levkk** [comment]
Hey @DeoLeung , give #79 a try and let me know if it works for you.

**Comment by DeoLeung** [comment]
I patch it and did a demo, which works
```sql
-- in pg 1
CREATE SCHEMA dm_1;


CREATE TABLE dm_1.test (
id INT
);

INSERT INTO dm_1.test VALUES (1), (3);

SELECT * FROM dm_1.test;

-- in pg2
CREATE SCHEMA dm_2;


CREATE TABLE dm_2.test (
id INT
);

INSERT INTO dm_2.test VALUES (2), (4);

SELECT * FROM dm_2.test;
```
* connect to pgcat
```bash
postgres@cb1fed2d6844:/$ psql -h pgcat -p 6432
Password for user postgres:
psql (13.7 (Debian 13.7-1.pgdg110+1))
Type "help" for help.
postgres=# show databases;
ERROR:  unrecognized configuration parameter "databases"
postgres=# SHOW DATABASES;
ERROR:  unrecognized configuration parameter "databases"
postgres=# SET SHARD TO '1';
SET SHARD
postgres=# select * from test;
 id
----
  2
  4
(2 rows)

postgres=# SET SHARD TO '0';
SET SHARD
postgres=# select * from test;
 id
----
  1
  3
(2 rows)

postgres=# select * from dm_2.test;
ERROR:  relation "dm_2.test" does not exist
LINE 1: select * from dm_2.test;
                      ^
postgres=# select * from dm_1.test;
 id
----
  1
  3
(2 rows)

postgres=# SET SHARD TO '1';
SET SHARD
postgres=# select * from dm_1.test;
ERROR:  relation "dm_1.test" does not exist
LINE 1: select * from dm_1.test;
                      ^
postgres=# select * from dm_2.test;
 id
----
  2
  4
(2 rows)

postgres=#
```

we start to deploy one to our test cluster for some real work. further feedback may take quite a while through.
we use to dispatch our sql with full identifier(including schema), so I think we don't really need the `search_path` setting.
having `SET SHARD`  to force following queries route to a specific db is enough for our scenario at the moment.
