### ISSUE TITLE
Splitting of read/write queries to replicas fail for CTEs

### ISSUE THREAD

**Issue by kevinelliott** [postgresml/pgcat#829]
**Describe the bug**
When `query_parser_read_write_splitting` is set to `true` and `primary_reads_enabled` set to `false`, any query that is sent as a CTE (thus, WITH ... UPDATE ... RETURNING ... SELECT) is incorrectly identified as having the ability to be split, and the SELECT is sent to the replica.

This results in an error like:
```
cannot execute SELECT in a read-only transaction
```

**To Reproduce**
1. Create a query that uses CTE format, such as:

```
WITH things AS (UPDATE things WHERE id = 1 RETURNING (id) SELECT id WHERE id = 1
```

2. Enable pgcat settings:
```
query_parser_enabled = true
query_parser_read_write_splitting = true
```

**Expected behavior**

Any CTE should detected as not-splittable, and remain on the primary entirely.

**Comment by phinitnan** [comment]
I am experiencing the same issue when use PGCat with Keycloak. The query "delete where in select" is failed.

**Comment by kevinelliott** [comment]
@drdrsh When I tried to use this, it seems to still fail for me. Perhaps I'm doing something wrong, or it's not implemented in all entirety?

**Comment by kevinelliott** [comment]
@drdrsh Wanted to check in again. I am still getting the error after using a build with this commit. Do you have any thoughts? Thanks!

**Comment by kevinelliott** [comment]
@jgoday Pinging you as well since I believe you were the one who submitted the fix.

**Comment by jgoday** [comment]
> @jgoday Pinging you as well since I believe you were the one who submitted the fix.

@kevinelliott Could you post the specific query that is giving you an error?

**Comment by kevinelliott** [comment]
> > @jgoday Pinging you as well since I believe you were the one who submitted the fix.
> 
> @kevinelliott Could you post the specific query that is giving you an error?

Sure! Let me activate it again and capture one.
