### ISSUE TITLE
Release 0.2.4 shows binary version 1.2.0

### ISSUE THREAD

**Issue by Preskton** [postgresml/pgcat#856]
**Describe the bug**

After installing from the source provided in version [`0.2.4`](https://github.com/postgresml/pgcat/archive/refs/tags/pgcat-0.2.4.tar.gz), the version reported by the `pgcat` binary is `1.2.0`.

**To Reproduce**

Preconditions: rust build environment ready and configured to `cargo build`.

1. Download the `0.2.4` release from https://github.com/postgresml/pgcat/archive/refs/tags/pgcat-0.2.4.tar.gz.
2. Unzip & untar.
3. Change to source directory and `cargo build --release`.
4. Run `pgcat --version`.

**Expected behavior**
I expected the version to match the Github release version: `0.2.4`.

**Actual behavior**

```
$ pgcat --version
pgcat 1.2.0
```

This might be expected - but it would be Neat (tm) if the GH release versions matched the binary's version.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: N/A
 - Version: N/A

**Additional context**

I'm working on building up an [Arch Linux AUR package](https://aur.archlinux.org/packages/pgcat) for `pgcat`. My `PKGBUILD` is as follows:

```
pkgname=pgcat
pkgver=0.2.4
pkgrel=1
pkgdesc="PostgreSQL pooler with sharding, load balancing and failover support. "
arch=('x86_64')
url="https://github.com/postgresml/pgcat"
license=('MIT')
depends=('gcc-libs')
makedepends=('cargo')
source=("$pkgname-$pkgver.tar.gz::https://github.com/postgresml/$pkgname/archive/refs/tags/pgcat-$pkgver.tar.gz")
sha512sums=('a316877f1ca79282bfb6005856a84963d356f89045d56cdd9fc4824f2fc1028988256303a1ed4d40dceead7bc2dc990c5bbdccbaa231825702331ac7184df6cf')
options=(!lto)

build() {
  cd "$pkgname-$pkgname-$pkgver"

  cargo build --release --locked
}

package() {
  cd "$pkgname-$pkgname-$pkgver"

  install -Dm755 "target/release/$pkgname" "$pkgdir/usr/bin/$pkgname"

  install -Dm644 "README.md" "$pkgdir/usr/share/doc/${pkgname}/README.md"
  install -Dm644 "LICENSE" "$pkgdir/usr/share/licenses/${pkgname}/LICENSE-MIT"
}
```

**Comment by drdrsh** [comment]
Hello, 

The Github release under the version `0.2.4` is a Chart release so it points to the chart version rather than the underlying binary version for PgCat. It would be difficult to keep that two matching given how the chart is a relatively new feature that is still undergoing iteration so it might see more releases than the binary.

**Comment by Preskton** [comment]
Got it. I didn't bother to check the other releases - it seems safe to say if a release starts with "v" it's an underlying pgcat release?

**Comment by drdrsh** [comment]
Today it is set up this way, yes. 

Although it seems like we could make this much clearer if the name of the release had the term "helm chart" in it.

**Comment by Preskton** [comment]
I suppose my other suggestion would be to *not* mark the helm chart releases as the latest release, since the repo is primarily about `pgcat` itself, not the helm chart.
